<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>admin</title>
    <?php echo $this->getChildHtml('head'); ?>
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

</head>

<body>
    <div>
        <?php echo $this->getChildHtml('header'); ?>
    </div>
    <div class="wrapper">
        <?php echo $this->getChildHtml('content'); ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('footer'); ?>
    </div>
</body>

</html>