<div class="container">
    <div class="title">Registration</div>
    <div class="content">
        <form method="POST" action="<?php echo $this->getUrl('customer/account/save') ?>">
            <div class="user-details">

                <input type="hidden" name="customer[customer_id]">

                <div class="input-box">
                    <label class="details" for="customer_email">Customer Email : </label>
                    <input type="email" name="customer[customer_email]" id="customer_email">
                </div>
                <div class="input-box">
                    <label class="details" for="first_name">First Name : </label>
                    <input type="text" name="customer[first_name]" id="first_name">
                </div>
                <div class=" input-box">
                    <label class="details" for="last_name">Last name : </label>
                    <input type="text" name="customer[last_name]" id="last_name">
                </div>


                <div class="input-box">
                    <label class="details" for="billing_city">Billing City : </label>
                    <input type="text" name="customer[billing_city]" id="billing_city">
                </div>

                <div class="input-box">
                    <label class="details" for="billing_region">Billing Region : </label>
                    <input type="text" name="customer[billing_region]" id="billing_region">
                </div>

                <div class="input-box">
                    <label class="details" for="billing_country">Billing Country : </label>
                    <input type="text" name="customer[billing_country]" id="billing_country">
                </div>

                <div class="input-box">
                    <label class="details" for="billing_address">Billing Address : </label>
                    <textarea name="customer[billing_address]" id="billing_address" cols="30" rows="5"></textarea>
                </div>

                <div class="input-box">
                    <label class="details" for="shipping_address">Shipping Address : </label>
                    <textarea name="customer[shipping_address]" id="shipping_address" cols="30" rows="5"></textarea>
                </div>
                <div class="input-box">
                    <label class="details" for="billing_phone">Billing Phone : </label>
                    <input type="number" name="customer[billing_phone]" id="billing_phone">
                </div>
                <div class="input-box">
                    <label class="details" for="shipping_city">Shipping City</label>
                    <input type="text" name="customer[shipping_city]" id="shipping_city">
                </div>

                <div class="input-box">
                    <label class="details" for="shipping_region">Shipping Region</label>
                    <input type="text" name="customer[shipping_region]" id="shipping_region">
                </div>

                <div class="input-box">
                    <label class="details" for="shipping_country">Shipping Country : </label>
                    <input type="text" name="customer[shipping_country]" id="shipping_country">
                </div>

                <div class="input-box">
                    <label class="details" for="shipping_phone">Shipping Phone : </label>
                    <input type="number" name="customer[shipping_phone]" id="shipping_phone">
                </div>
                <div class="input-box">
                    <label class="details" for="password">Password : </label>
                    <input type="text" name="customer[Password]" id="Password">
                </div>
                <div class="button">
                    <input type="submit" value="Register">
                </div>
                <div class="buttonlog">
                    <a href="<?php echo $this->getUrl('customer/account/login') ?>">Already You have Account?</a>
                </div>
        </form>
    </div>
</div>