<form method="POST" action="<?php echo $this->getUrl('customer/account/login') ?>">
    <section>
        <div class="signin">
            <div class="content">
                <h2>Sign In</h2>
                <div class="form">
                    <div class="inputBox">
                        <input type="email" name="login[customer_email]" id="loginemail" autocomplete="off"
                            required><i>Username</i>
                    </div>

                    <div class="inputBox">
                        <input type="password" name="login[password]" id="loginpass" required><i>Password</i>
                    </div>

                    <div class="links"> <a
                            href="<?php echo Mage::getBaseUrl('customer/account/forgotPassword'); ?>">Forgot
                            Password</a> <a href="<?php echo $this->getUrl('customer/account/register') ?>"
                            class="register-link">Signup</a>
                    </div>
                    <div class="inputBox">
                        <input type="submit" value="Login">
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>