<?php
// echo "<pre>";
$orderData = $this->getOrderData();
//  $orderData = $this->getOrderItemData($dataa->getData()->getOrderId());
// print_r($this->getProductData($orderData->getProductId()->getData()));
// die;

// print_r($dataa->getData());
// die;
foreach ($orderData->getData() as $data):
    // print_r($data);
    // die;
    foreach ($this->getOrderItemData($data->getOrderId())->getData() as $orderData):
        // print_r($orderData);
        // die;
        foreach ($this->getProductData($orderData->getProductId())->getData() as $productData):
            // foreach ($this->getAddressData($productData)->getData() as $addressData):
            $addressData = $this->getAddressData($productData)->getData();
            // print_r($addressData);
            // die;
            ?>
            <div class="container-fluid my-5 d-sm-flex justify-content-center">
                <div class="orderCard px-2">
                    <div class="card-header bg-white">
                        <div class="header-card-order row justify-content-between">
                            <div class="col">
                                <p class="text-muted"> Order Number :<span class="font-weight-bold text-dark">
                                        <?php echo $data->getOrderNumber(); ?>
                                    </span></p>
                                </p>
                            </div>
                            <div class="flex-col my-auto">
                                <h6 class="ml-auto mr-3">
                                    <a class="productDetails" href="#">View Details</a>
                                </h6>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="media flex-column ">
                            <div class="media-body ">
                                <h5 class="bold">
                                    <?php echo $orderData->getProductName(); ?>
                                </h5>
                                <p class="text-muted">Qty :
                                    <?php echo $orderData->getQty(); ?>
                                </p>
                                <h4 class="mt-3 mb-4 bold"> <span class="mt-5">&#x20B9;</span>
                                    <?php echo $orderData->getPrice(); ?>
                                    <!-- <span class="small text-muted">
                                        via (COD) </span> -->
                                </h4>
                                <h4 class="total mt-3 mb-4 bold">Total : <span class="mt-5">&#x20B9;</span>
                                    <?php echo $data->getgrandTotal(); ?>
                                    <!-- <span class="small text-muted">
                                        via (COD) </span> -->
                                </h4>
                            </div>
                            <div class="orderAddress">
                                <h2>
                                    <?php echo $addressData['billing_address']; ?>
                                    <?php echo $addressData['billing_city']; ?>
                                </h2>
                            </div>
                            <img class="align-self-center img-fluid"
                                src="<?php echo $this->imageLink($productData->getImageLink()); ?>">
                        </div>
                    </div>
                    <div class="card-footer  bg-white px-sm-3 pt-sm-4 px-0">
                        <div class="row text-center  ">
                            <div class="col my-auto  border-line ">
                                <h5>
                                    <?php echo $data->getStatus() ?>
                                </h5>
                            </div>
                            <!-- <div class="col  my-auto  border-line ">
                                <h5><a href="<?php //echo Mage::getBaseUrl('customer/view/cancel?id='.$data->getOrderId());             ?>"> Cancle </a></h5>
                            </div> -->

                            <div class="col  my-auto  border-line cancel">
                                <?php if ($data->getStatus() == 'completed') { ?>
                                    <h5>Order Completed</h5>
                                <?php } else { ?>
                                    <h5>
                                    <a href="<?php echo $this->getUrl('customer/view/cancel?id=' . $data->getOrderId()); ?>">
                                            Cancle </a>
                                    </h5>
                                <?php } ?>
                            </div>

                            <div class="col my-auto border-line ">
                                <h5>Pre-pay</h5>
                            </div>
                            <div class="col  my-auto mx-0 px-0 "><img class="img-fluid cursor-pointer"
                                    src="https://img.icons8.com/ios/50/000000/menu-2.png" width="30" height="30"></div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endforeach; ?>
<!-- <?php //endforeach;                        ?> -->