<?php
// echo "<pre>";
$orderData = $this->getOrderData();
?>

<div class="container-new">
    <table class="table-new">
        <thead>
            <tr>
                <th>Order Id</th>
                <th>Order Number</th>
                <th>Date</th>
                <th>Grand Total</th>
                <th>Status</th>
                <th>Update Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($orderData->getData() as $data) { ?>
                <tr>
                    <td>
                        <?php echo $data->getOrderId(); ?>
                    </td>
                    <td>
                        <?php echo $data->getOrderNumber(); ?>
                    </td>
                    <td>
                        <?php echo $data->getDate(); ?>
                    </td>
                    <td>
                        <?php echo $data->getGrandTotal(); ?>
                    </td>
                    <td class="orderStatus">
                        <?php echo $data->getStatus(); ?>
                    </td>
                    <td>
                        <form method="post" action="<?php echo $this->getUrl('admin/sales/save'); ?>" class="statusForm">
                            <input type="hidden" name="status[order_id]" value="<?php echo $data->getId() ?>">
                            <div><select name="status[status]" class="statuses">
                                    <?php $statusOptions = $this->getStatusOption(); ?>
                                    <?php foreach ($statusOptions as $key => $value) { ?>
                                        <option value="<?php echo $key ?>">
                                            <?php echo $value ?>
                                        </option>
                                    <?php } ?>
                                </select></div>
                            <div>
                                <input id="statusSubmit" type="submit" value="Update">
                            </div>
                        </form>
                    </td>
                    <td>
                        <?php if ($data->getStatus() == 'cancel_request') { ?>
                            <a href="<?php echo $this->getUrl('admin/sales/accept?id=' . $data->getOrderId()); ?>"><button><i
                                        class="fa fa-check"></i></button></a>
                            <a href="<?php echo $this->getUrl('admin/sales/reject?id=' . $data->getOrderId()); ?>"><button><i
                                        class="fa fa-times"></i></button></a>
                        <?php } ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->getUrl('admin/sales/view?id='.$data->getOrderId()); ?>"> View </a>
                    </td>
                    <!-- <td id="statusDisplay_<?php //echo $data->getOrderId();         ?>">
                                <?php //echo $data->getStatus();         ?>
                                </td>
                                <td>
                                    <form id="orderForm_<?php //echo $data->getOrderId();         ?>" method="post" action="">
                                        <input type="hidden" name="order[order_id]" value="<?php //echo $data->getId()         ?>">
                                        <select class="statusSelect" name="order[status]" onchange="submitForm(this)">
                                            <option value="pending">Pending</option>
                                            <option value="shipped">Shipped</option>
                                            <option value="canceled">Canceled</option>
                                            <option value="declined">Declined</option>
                                            <option value="funded">Funded</option>
                                            <option value="completed">Completed</option>
                                        </select>
                                    </form>
                                </td> -->
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<!-- <script>
    function submitForm(selectElement) {
        // Get the selected value
        var selectedValue = selectElement.value;

        // Get the parent form
        var form = selectElement.parentNode;

        // Get the corresponding statusDisplay td
        var statusDisplayId = form.id.replace("orderForm", "statusDisplay");
        var statusDisplay = document.getElementById(statusDisplayId);

        // Update the content of statusDisplay td
        statusDisplay.innerHTML = selectedValue;

        // Submit the form
        form.action = "<?php echo Mage::getBaseUrl('admin/order/save') ?>";
        form.submit();
    }
</script> -->