<?php
echo "<pre>";
// $orderData = $this->getOrderData();
$orderData = $this->getOrderData();
print_r($orderData);
$customerData = $this->getCustomerData($orderData->getCustomerId());
print_r($customerData);
$orderItemData = $this->getOrderItemData($orderData->getOrderId());
print_r($orderItemData->getData());
// $productData = $this->getProductData($orderItemData->getproductId());
// print_r($productData->getData());
?>

<div class="container-new">
    <div>

        <table class="table-new">
            <thead>
                <tr>
                    <th>Customer Name</th>
                    <th>Customer Email</th>
                    <th>Contact</th>
                    <th>Address</th>
                </tr>
            </thead>
            <tbody>
                <?php
                //foreach ($orderData->getData() as $data) {                   ?>
                <tr>
                    <td>
                        <?php echo $customerData->getFirstName(); ?>
                    </td>
                    <td>
                        <?php echo $customerData->getCustomerEmail(); ?>
                    </td>
                    <td>
                        <?php echo $customerData->getBillingPhone(); ?>
                    </td>
                    <td>
                        <?php echo $customerData->getBillingAddress(); ?>
                    </td>
                </tr>
                <?php //}                   ?>
            </tbody>

    </div>
    <div>
        <table class="table-new">
            <thead>
                <tr>
                    <th>Item Image</th>
                    <th>Sku</th>
                    <th>Price</th>
                    <th>Row Total</th>
                    <th>Grand Total</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($orderItemData->getData() as $itemData) {
                foreach ($this->getProductData($itemData->getproductId())->getData() as $productData) {

                    print_r($productData); ?>
                    <tr>
                        <td>
                            <?php echo $itemData->getFirstName(); ?>
                        </td>
                        <td>
                            <?php echo $itemData->getCustomerEmail(); ?>
                        </td>
                        <td>
                            <?php echo $customerData->getBillingPhone(); ?>
                        </td>
                        <td>
                            <?php echo $itemData->getBillingAddress(); ?>
                        </td>
                    </tr>
                <?php } ?>
                <?php } ?>
            </tbody>
    </div>
    </table>
</div>