<form method="POST" action="<?php echo Mage::getBaseUrl('loancalculator/loancalculator/save') ?>">
    <?php $rate = $this->getRateList(); ?>

    <div class="row">
        <input type="hidden" name="loan[id]" id="username">
    </div>
    <div class="row">
        <input type="hidden" name="loan[session_id]" id="username" value="<?php echo $this->getIdSession(); ?>">
    </div>
    <div class="row">
        <label for="username">username : </label>
        <input type="text" name="loan[user_name]" id="username">
    </div>
    <div class="row">
        <label for="loan_amount">loan_amount</label>
        <input type="number" name="loan[loan_amount]" id="loan_amount">
    </div>
    <div class="row">
        <label for="monthly_amount">monthly amount</label>
        <input type="number" name="loan[monthly_amount]" id="monthly_amount">
    </div>
    <div class="row">
        <label for="term">term years</label>
        <select name="loan[term]" id="term">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20">20</option>
        </select>
    </div>
    <div class="row">
        <label for="bankcode">banks :</label>
        <select name="loan[bank_code]">
            <?php foreach ($rate->getData() as $_bank): ?>
                <option value="<?php echo $_bank->getBankCode() ?>">
                    <?php echo $_bank->getBankCode(); ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="row">
        <input type="submit" name="submit" value="Calculate">
    </div>
</form>