<?php

$productCollection = $this->getProduct();
$URL = Mage::getBaseUrl('admin/catalog_product');
// $productCollection->addFieldToFilter('name', 'abc');
// $productCollection->addFieldToFilter('product_id', ['in' => [55]]);
// $productCollection->addFieldToFilter('sku', ['like'=>'%abc']);
// $productCollection->getData();
?>
<div class="tbl">
    <table border="1px">
        <tr>
            <th>id</th>
            <th>Sku</th>
            <th>Name</th>
            <!-- <th>Color</th> -->
            <th>Size</th>
            <th>Description</th>
            <!-- <th>ImageLink</th> -->
            <th>Link</th>
            <th>Category ID</th>
            <th>Price</th>
            <!-- <th>Mfr Cost</th> -->
            <!-- <th>Shipping Cost</th> -->
            <th>Total Cost</th>
            <!-- <th>Margin Percentage</th> -->
            <!-- <th>Min Price</th> -->
            <th>Status</th>
            <th colspan=2>Action</th>
        </tr>
        <?php
        foreach ($productCollection->getData() as $product) { ?>
            <tr>
                <td>
                    <?php print_r($product->getProductId()); ?>
                </td>
                <td>
                    <?php print_r($product->getSku()); ?>
                </td>
                <td>
                    <?php print_r($product->getName()); ?>
                </td>
                <!-- <td>
                    <?php //print_r($product->getColor());  ?>
                </td> -->
                <td>
                    <?php print_r($product->getSize()); ?>
                </td>
                <td>
                    <?php print_r($product->getDescription()); ?>
                </td>
                <!-- <td>
                    <?php //print_r($product->getImageLink());  ?>
                </td> -->
                <td>
                    <?php print_r($product->getLink()); ?>
                </td>
                <td>
                    <?php print_r($product->getCategoryId()); ?>
                </td>
                <td>
                    <?php print_r($product->getPrice()); ?>
                </td>
                <!-- <td>
                    <?php //print_r($product->getMfrCost());  ?>
                </td> -->
                <!-- <td>
                    <?php //print_r($product->getShippingCost());  ?>
                </td> -->
                <td>
                    <?php print_r($product->getTotalCost()); ?>
                </td>
                <!-- <td>
                    <?php //print_r($product->getMarginPercentage());  ?>
                </td> -->
                <!-- <td>
                    <?php //print_r($product->getMinPrice());   ?>
                </td> -->
                <td>
                    <?php print_r($product->getStetus()); ?>
                </td>
                <td>
                    <a href="<?php echo $URL; ?>/form?id=<?php print_r($product->getProductId()); ?>" type="button"
                        id="update"> Update </a>
                </td>
                <td>
                    <a href="<?php echo $URL; ?>/delete?id=<?php print_r($product->getProductId()); ?>" type="button"
                        id="Delete"> Delete </a>
                </td>
            </tr>

        <?php } ?>
    </table>
</div>