<?php
$productData = $this->getProductData();
$imagePath = Mage::getBaseUrl("media/product/");

?>
<div class="prodcard">
    <?php foreach ($productData->getData() as $product) { ?>
        <a href="http://localhost/practice/Mvc/catalog/product/view?id=<?php echo $product->getProductId(); ?>">
            <div class="card">
                <img src="<?php echo $imagePath . $product->getImageLink();
                ; ?>" alt="Product Image">

                <table>
                    <tr>
                        <th>ID</th>
                        <td>
                            <?php echo $product->getProductId(); ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Color</th>
                        <td>
                            <?php echo $product->getColor(); ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Price</th>
                        <td>
                            <?php echo $product->getPrice(); ?>
                        </td>
                    </tr>

                    <tr>
                        <th>Status</th>
                        <td
                            class="<?php echo ($product->getStetus() == 'Enabled') ? 'status-active' : 'status-inactive'; ?>">
                            <?php echo $product->getStetus(); ?>
                        </td>
                    </tr>

                </table>
            </div>
        </a>
    <?php } ?>
</div>

<!-- </table> -->
<!-- </div> -->