<header>
    <div class="page-header">
        <div class="logo">
            <a href="<?php echo Mage::getBaseUrl(''); ?>"><img id="headlogo" src=<?php echo Mage::getBaseUrl() . "skin/images/icon.png" ?> alt="Your Logo"></a>
        </div>
        <div class="pill-nav" id="myDIV">
            <ul>
                <div class="dropdown">
                    <a class="btn" href="<?php echo Mage::getBaseUrl("admin"); ?>"> Dashboard </a>
                    <a class="btn" href="<?php echo Mage::getBaseUrl("admin/sales"); ?>"> Order </a>
                </div>
                <div class="dropdown">
                    <a class="btn"> Product </a>
                    <div class="dropdown-content">
                        <a href="<?php echo Mage::getBaseUrl("admin/import"); ?>">Import CSV </a>
                        <a href="<?php echo Mage::getBaseUrl("admin/catalog_product/form"); ?>">Product Form</a>
                        <a href=" <?php echo Mage::getBaseUrl("admin/catalog_product/list"); ?>">Product
                            List</a>
                    </div>
                </div>
                <div class="dropdown">
                    <a class="btn"> Import </a>
                    <div class="dropdown-content">
                        <a href="<?php echo Mage::getBaseUrl("admin/import/form"); ?>">Upload CSV </a>
                        <a href="<?php echo Mage::getBaseUrl("admin/import/list"); ?>">Read Csv</a>
                        <a href=" <?php echo Mage::getBaseUrl("admin/import/readedlist"); ?>">Import Csv</a>
                    </div>
                </div>
                <div class="dropdown">
                    <a class="btn"> Category </a>
                    <div class="dropdown-content">
                        <a href="<?php echo Mage::getBaseUrl("admin/catalog_category/form"); ?>">Category
                            Form</a>
                        <a href=" <?php echo Mage::getBaseUrl("admin/catalog_category/list"); ?>">Category
                            List</a>
                    </div>
                </div>
                <div class="dropdown">
                    <a class="btn"> Banner </a>
                    <div class="dropdown-content">
                        <a href="<?php echo Mage::getBaseUrl("admin/banner/form"); ?>">Banner Form</a>
                        <a href=" <?php echo Mage::getBaseUrl("admin/banner/list"); ?>">Category List</a>
                    </div>
                </div>
                <a class="btn" href="<?php echo Mage::getBaseUrl("admin/user/logout"); ?>">Log Out</a>
            </ul>
        </div>

    </div>
    <!-- <div class="buttondiv"> -->
    <!-- <div class="btn row">
                <a href="<?php //echo Mage::getBaseUrl('customer/Account/login');                   ?>" style="--navAni:5"><button
                        type="button">User</button></a>
            </div> -->
    <!-- <div class="btn row">
                <a href="<?php //echo Mage::getBaseUrl('Admin/user/login');                 ?>" style="--navAni:5"><button
                        type="button">Admin</button></a>
            </div> -->
    <!-- <div class="btn row">
                <a href="<?php //echo Mage::getBaseUrl('admin/user/logout');       ?>" style="--navAni:5"><button
                        type="button">Logout</button></a>
            </div> -->
    <!-- </div> -->
</header>
<!-- <header>
    <div class="header">
        <div class="page-header">
            <div class="logo">
                <a href="<?php //echo Mage::getBaseUrl('');      ?>"><img id="headlogo" src=<?php //echo Mage::getBaseUrl() . "skin/images/icon.png"      ?> alt="Your Logo"></a>
            </div>
            <div class="header-right">
                <div class="pill-nav" id="myDIV">
                    <ul>
                        <div class="dropdown">
                            <a class="btn" href="<?php //echo Mage::getBaseUrl("");      ?>"> Home </a>
                            <a class="btn" href="<?php //echo Mage::getBaseUrl("admin");      ?>"> Admin Dashbord </a>
                            <a class="btn" href="<?php //echo Mage::getBaseUrl("admin/order");      ?>"> All Order </a>
                        </div>
                        <div class="dropdown">
                            <a class="btn"> Product </a>
                            <div class="dropdown-content">
                                <a href="<?php //echo Mage::getBaseUrl("admin/catalog_product/form");      ?>">Product Form</a>
                                <a href=" <?php //echo Mage::getBaseUrl("admin/catalog_product/list");      ?>">Product
                                    List</a>
                            </div>
                        </div>
                        <div class="dropdown">
                            <a class="btn"> Category </a>
                            <div class="dropdown-content">
                                <a href="<?php //echo Mage::getBaseUrl("admin/catalog_category/form");      ?>">Category
                                    Form</a>
                                <a href=" <?php //echo Mage::getBaseUrl("admin/catalog_category/list");      ?>">Category
                                    List</a>
                            </div>
                        </div>
                        <div class="dropdown">
                            <a class="btn"> Banner </a>
                            <div class="dropdown-content">
                                <a href="<?php //echo Mage::getBaseUrl("admin/banner/form");      ?>">Banner Form</a>
                                <a href=" <?php //echo Mage::getBaseUrl("admin/banner/list");      ?>">Category List</a>
                            </div>
                        </div>
                        <a class="btn" href="<?php //echo Mage::getBaseUrl("admin/user/logout");      ?>">Log Out</a>
                    </ul>
                    
                </div>
            </div>
        </div>
</header> -->
<!-- <div class="header">
    <a href="#"><img id="logo" src=<?php //echo Mage::getBaseUrl() . "\skin\image\ccc.jpg"      ?> alt="Your Logo"></a>
    <div class="header-right">
        <div class="pill-nav" id="myDIV">
            <ul>
                <div class="dropdown">
                    <a class="btn" href="<?php //echo Mage::getBaseUrl("");      ?>"> Home </a>
                    <a class="btn" href="<?php //echo Mage::getBaseUrl("admin");      ?>"> Admin Dashbord </a>
                    <a class="btn" href="<?php //echo Mage::getBaseUrl("admin/order");      ?>"> All Order </a>
                </div>
                <div class="dropdown">
                    <a class="btn"> Product </a>
                    <div class="dropdown-content">
                        <a href="<?php //echo Mage::getBaseUrl("admin/catalog_product/form");      ?>">Product Form</a>
                        <a href=" <?php //echo Mage::getBaseUrl("admin/catalog_product/list");      ?>">Product List</a>
                    </div>
                </div>
                <div class="dropdown">
                    <a class="btn"> Category </a>
                    <div class="dropdown-content">
                        <a href="<?php //echo Mage::getBaseUrl("admin/catalog_category/form");      ?>">Category Form</a>
                        <a href=" <?php //echo Mage::getBaseUrl("admin/catalog_category/list");      ?>">Category List</a>
                    </div>
                </div>
                <div class="dropdown">
                    <a class="btn"> Banner </a>
                    <div class="dropdown-content">
                        <a href="<?php //echo Mage::getBaseUrl("admin/banner/form");      ?>">Banner Form</a>
                        <a href=" <?php //echo Mage::getBaseUrl("admin/banner/list");      ?>">Category List</a>
                    </div>
                </div>
                <a class="btn" href="<?php //echo Mage::getBaseUrl("admin/user/logout");      ?>">Log Out</a>
            </ul>
        </div>
    </div>
</div> -->
<script>
    window.addEventListener('scroll', function () {
        var header = document.querySelector('header');

        // Add a class to the header when scrolling down
        if (window.scrollY > 0) {
            header.classList.add('scrolled');
        } else {
            header.classList.remove('scrolled');
        }
    });
</script>