<!-- <footer>
    <div class="footer-container">
        <p>&copy; 2024 Your Website. All rights reserved.</p>
    </div>
</footer> -->

<footer class="footer-distributed">

    <div class="footer-left">

        <div class="logo">
            <img id="footlogo" src=<?php echo $this->getUrl('') . "skin/images/icon.png" ?> alt="Your Logo">
            <!-- <a href="#">Logo.</a> -->
        </div>

        <p class="footer-links">
            <a href="#" class="link-1">Home</a>
            <a href="#">Blog</a>
            <a href="#">Pricing</a>
            <a href="#">About</a>
            <a href="#">Faq</a>
            <a href="#">Contact</a>
        </p>

        <p class="footer-company-name footcenter">Company Name © 2024</p>
    </div>

    <div class="footer-center">

        <div>
            <i class="fa fa-map-marker footcenter"></i>
            <p><span>444 S. Cedros Ave</span> Solana Beach, California</p>
        </div>

        <div>
            <i class="fa fa-phone footcenter"></i>
            <p>+1.555.555.5555</p>
        </div>

        <div>
            <i class="fa fa-envelope footcenter"></i>
            <p><a href="mailto:support@company.com">support@company.com</a></p>
        </div>

    </div>

    <div class="footer-right">

        <p class="footer-company-about">
            <span>About the company</span>
            Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus
            vehicula sit amet.
        </p>

        <div class="footer-icons">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-linkedin-in"></i></a>

        </div>

    </div>

</footer>