<!-- <header>

    <ul>
        
        <li><a class="floatleft" href="#about">About</a></li>
        <li><a class="floatleft" href="#contact">Contact</a></li>
        <li><a class="floatleft" href="#news">News</a></li>
        <li><a class="floatleft" class="active" href="#home">Home</a></li>
    </ul>
</header> -->
<header>
    <div class="page-header">
        <div class="logo">
            <a href="<?php echo Mage::getBaseUrl(''); ?>"><img id="headlogo" src=<?php echo Mage::getBaseUrl() . "skin/images/icon.png" ?> alt="Your Logo"></a>
        </div>
        <div class="buttondiv">
            <div class="btn row">
                <a href="<?php echo Mage::getBaseUrl('customer/Account/login'); ?>" style="--navAni:5"><button
                        type="button">User</button></a>
            </div>

            <div class="btn row">
                <a href="<?php echo Mage::getBaseUrl('Admin/user/login'); ?>" style="--navAni:5"><button
                        type="button">Admin</button></a>
            </div>
            <div class="btn row">
                <a href="<?php echo Mage::getBaseUrl('customer/Account/logout'); ?>" style="--navAni:5"><button
                        type="button">Logout</button></a>
            </div>
        </div>
</header>