<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php $js = $this->getJs(); ?>
    <?php if (count($js)): ?>
        <?php foreach ($js as $_js): ?>
            <script type="" src="<?php echo $_js; ?>"></script>
        <?php endforeach; ?>
    <?php endif ?>

    <?php $css = $this->getCss(); ?>
    <?php if (count($css)): ?>
        <?php foreach ($css as $_css): ?>
            <style type="" src="<?php echo $_css; ?>"></style>
        <?php endforeach; ?>
    <?php endif ?>
</body>

</html>