<header>
    <div class="page-header">
        <div class="logo">
            <a href="<?php echo Mage::getBaseUrl(''); ?>"><img id="headlogo" src=<?php echo Mage::getBaseUrl() . "skin/images/icon.png" ?> alt="Your Logo"></a>
        </div>
        <div class="buttondiv">
            <div class="btn row">
                <a href="<?php echo Mage::getBaseUrl(''); ?>" style="--navAni:5">Home</a>
            </div>
            <div class="btn row">
                <a href="<?php echo Mage::getBaseUrl(''); ?>" style="--navAni:5">About</a>
            </div>
            <div class="btn row">
                <div class="pill-nav" id="myDIV">
                    <ul>
                        <div class="dropdown">
                            <a class="btn"> Shop </a>
                            <div class="dropdown-content dropdownDiv">
                                <a href="<?php echo Mage::getBaseUrl("catalog/category/view?id=1"); ?>">Sofa</a>
                                <a href=" <?php echo Mage::getBaseUrl("catalog/category/view?id=2"); ?>">Jeans</a>
                                <a href=" <?php echo Mage::getBaseUrl("catalog/category/view?id=3"); ?>">T-Shirts</a>
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
            <div class="btn row">
                <a href="<?php echo Mage::getBaseUrl(''); ?>" style="--navAni:5">Contact</a>
            </div>
              <!--<div class="btn row">
                <a href="<?php //echo Mage::getBaseUrl('cart'); ?>" style="--navAni:5">Cart</a>
            </div>-->
            <?php if ($this->userLogin()): ?>
                <div class="btn row sign">
                    <!-- <h5>Welcome
                        <?php //echo $this->getCustomerName();      ?>
                    </h5> -->
                    <a href="<?php echo Mage::getBaseUrl('customer/Account/dashboard'); ?>" style="--navAni:5"><img id="logout"
                            src=<?php echo Mage::getBaseUrl() . "skin/images/user.png" ?> alt="Your Logo"></a>
                </div>
            <?php else: ?>
                <div class="btn row sign">
                    <a href="<?php echo Mage::getBaseUrl('customer/Account/login'); ?>" style="--navAni:5"><span> Sign in</span><img id="login"
                            src=<?php echo Mage::getBaseUrl() . "skin/images/user.png" ?> alt="Your Logo"></a>
                </div>
            <?php endif; ?>

            <!-- <div class="btn row">
                <a href="<?php //echo Mage::getBaseUrl('Admin/user/login');             ?>" style="--navAni:5"><button
                        type="button">Admin</button></a>
            </div> -->
        </div>
</header>
<script>
    window.addEventListener('scroll', function () {
        var header = document.querySelector('header');

        // Add a class to the header when scrolling down
        if (window.scrollY > 0) {
            header.classList.add('scrolled');
        } else {
            header.classList.remove('scrolled');
        }
    });
</script>