<?php
$productData = $this->getProductData();
?>
<div class="wrapper">

    <?php foreach ($productData->getData() as $product): ?>
        <form method="POST" action="<?php echo $this->getUrl('sales/quote/add') ?>">
            <div class="product-img">
                <img class="imgproduct" src="<?php echo $this->getUrl('media/product/') . $product->getImageLink(); ?>"
                    alt="">
            </div>
            <div class="row">
                <input type="hidden" name="cart[product_id]" value="<?php echo $product->getProductId(); ?>">
            </div>
            <div class="product-info">
                <div class="product-text">
                    <h1>
                        <?php echo $product->getName(); ?>
                    </h1>
                    <p>
                        <?php echo $product->getDescription(); ?>
                    </p>
                </div>
                <div class="quantity-box">
                    <?php if ($product->getInventory()): ?>
                        <span class="quantity-label">Quantity : </span>
                        <input class="qty" type="number" name="cart[qty]" class="quantity-input" value="1" min="1"
                            max="<?php echo $product->getInventory() ?>">
                    <?php else: ?>
                        <span style="color:red;">Out of Stock</span>
                    <?php endif; ?>
                </div>
                <div class="product-price-btn">
                    <p><span>Price :
                            <?php echo $product->getPrice() ?>
                        </span>$</p>
                </div>
                <div>
                    <input type="submit" class="add-to-cart" value="Add to Cart">
                </div>
            </div>
        </form>
    <?php endforeach; ?>
</div>