<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="form" style="border:6px solid black; width:40vw; padding: 15px; margin-left:auto; margin-right:auto;">
        <h2 style="text-align:center">Add Category Form</h2>
        <form method="POST" action="">
            <div class="row">
                <label for="category">Category Name : </label>
                <input type="text" name="catalog_category[category_name]" id="category">
            </div>
            <div class="row">
                <label for="status">Status : </label>
                <input type="text" name="catalog_category[status]" id="status">
            </div>
        </form>
    </div>
</body>

</html>